[package]
name = "stage0"
version = "0.1.0"
authors = ["Clemens <panemlp@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "lib" }
colored = "2.0.0"